export const spicy = [{
    name:"ผัดกะเพราหมูสับ",
    img:"img-spicy/1.jpg"
},
{
    name:"ผัดกะเพรากุ้ง",
    img:"img-spicy/2.jpg"
},
{
    name:"กะเพราเนื้อไข่ดาว",
    img:"img-spicy/3.jpg"
},
{
    name:"ผัดกะเพราหมูกรอบ",
    img:"img-spicy/4.jpg"
},
{
    name:"ผัดกะเพราไก่",
    img:"img-spicy/5.jpg"
},
{
    name:"ผัดกะเพราปลาหมึก",
    img:"img-spicy/6.jpg"
},
{
    name:"ผัดกะเพราไข่เยี่ยวม้าหมูสับ",
    img:"img-spicy/7.jpg"
},
{
    name:"ผัดกะเพราทะเล",
    img:"img-spicy/8.jpg"
},
{
    name:"ผัดกะเพรากุนเชียง",
    img:"img-spicy/9.jpg"
},
{
    name:   "ผัดกะเพราหมูยอ",
    img:"img-spicy/10.jpg"
},
{
    name: "ผัดขี้เมาหมู",
    img:"img-spicy/11.jpg"
},
{
    name:"ผัดขี้เมาไก่",
    img:"img-spicy/12.jpg"
},
{
    name:"ผัดขี้เมาทะเล",
    img:"img-spicy/13.jpg"
},
{
    name:"ผัดขี้เมาเนื้อ",
    img:"img-spicy/14.jpg"
},
{
    name:"มาม่าผัดขี้เมาหมูกรอบ",
    img:"img-spicy/15.jpg"
},
{
    name:"มาม่าผัดขี้เมาทะเล",
    img:"img-spicy/16.jpg"
},
{
    name:"มาม่าผัดขี้เมาหมู",
    img:"img-spicy/17.jpg"
},
{
    name:"ผัดพริกแกงไก่",
    img:"img-spicy/18.jpg"
},
{
    name:"ผัดพริกแกงเนื้อ",
    img:"img-spicy/19.jpg"
},
{
    name:"ผัดพริกแกงทะเล",
    img:"img-spicy/20.jpg"
},
{
    name:"ผัดพริกแกงหมู",
    img:"img-spicy/21.jpg"
},
{
    name:"หมูผัดพริกเผา",
    img:"img-spicy/22.jpg"
},
{
    name:"ปลาหมึกผัดพริกเผา",
    img:"img-spicy/23.jpg"
},
{
    name:"ยำวุ้นเส้น",
    img:"img-spicy/24.jpg"
},
{
    name:"ยำมาม่า",
    img:"img-spicy/25.jpg"
},
{
    name:"ยำปลากระป๋อง",
    img:"img-spicy/26.jpg"
},
{
    name: "ต้มยำกุ้ง",
    img:"img-spicy/27.jpg"
},
{
    name: "ผัดพริกแกงปลาหมึก",
    img:"img-spicy/28.jpg"
},
{
    name: "กะเพราเต้าหู๋๋ไข่",
    img:"img-spicy/29.jpg"
}, ];